default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  database: sample_app
  username: root
  password: "123456"
development:
  <<: *default

test:
  <<: *default
  database: <%= ENV["DATABASE_NAME_TEST"] %>

staging:
  <<: *default

production:
<<: *default